
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-04
owner: ucsb-cs156-f24
repo_name: team01-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestController","number":72,"title":"Michael help request controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/72"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestTable","number":70,"title":"Add HelpRequest database table","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/70"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-delete","number":69,"title":"Alvin RecommendationRequest Get Added #24","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/69"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-put","number":68,"title":"Alvin RecommendationRequest Put Added #23","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/68"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-get","number":67,"title":"Alvin RecommendationRequest Get Added #22","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/67"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-controller","number":66,"title":"Alvin RecommendationRequest Controller, Post, Get Added #21","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/66"}]
