
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-04
owner: ucsb-cs156-f24
repo_name: team01-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestGet","number":75,"title":"Michael help request get","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/75"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestPut","number":74,"title":"Michael help request put","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/74"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestDelete","number":73,"title":"Michael help request delete","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/73"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestController","number":72,"title":"Michael help request controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/72"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestTable","number":70,"title":"Add HelpRequest database table","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/70"}]
