
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-04
owner: ucsb-cs156-f24
repo_name: team01-f24-04
pull_requests: [{"author":{"id":"U_kgDOB_ueCQ","is_bot":false,"login":"nilay-kundu","name":"Nilay Kundu"},"headRefName":"nk-MenuItemReview-get","number":52,"title":"MenuItemReview GET","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/52"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-Get","number":49,"title":"UCSBDiningCommonMenuItem Get function added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/49"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItem-Put","number":46,"title":"UCSB DiningCommonMenuItem Put function added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/46"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-UCSBDiningMenuItem-Delete","number":45,"title":"UCSBDiningCommonMenuItem - Delete Function Added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/45"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-controller","number":44,"title":"UCSBDiningCommonMenuItems - Controller, Post, GetAll Work","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/44"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-create-db","number":43,"title":"Nikhil DiningCommonMenuItems Created Database","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/43"}]
