
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-04
owner: ucsb-cs156-f24
repo_name: team01-f24-04
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-controller","number":66,"title":"Alvin recommendation request controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/66"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-UCSBOrgs-delete","number":64,"title":"UCSBOrganizations: added DELETE","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/64"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-UCSBOrgs-put","number":63,"title":"UCSBOrganizations: added PUT","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/63"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-UCSBOrgs-get","number":57,"title":"UCSBOrganizations: added GET","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/57"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-UCSBOrgs-controller","number":55,"title":"UCSBOrganizations: controller, get and post","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/55"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-Get","number":49,"title":"UCSBDiningCommonMenuItem Get function added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/49"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItem-Put","number":46,"title":"UCSB DiningCommonMenuItem Put function added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/46"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-UCSBDiningMenuItem-Delete","number":45,"title":"UCSBDiningCommonMenuItem - Delete Function Added","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/45"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-controller","number":44,"title":"UCSBDiningCommonMenuItems - Controller, Post, GetAll Work","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/44"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-DiningMenuItems-create-db","number":43,"title":"Nikhil DiningCommonMenuItems Created Database","url":"https://github.com/ucsb-cs156-f24/team01-f24-04/pull/43"}]
